#!/bin/bash
# Builds, notarises and packages TapSpaces for distribution.
#
# Notarisation credentials live in the macOS Keychain under the profile name
# below, put there once with:
#
#   xcrun notarytool store-credentials tapspaces \
#       --apple-id "<apple-id>" --team-id "<team-id>"
#
# No secret is ever passed on the command line or stored in this repository.
set -euo pipefail
cd "$(dirname "$0")"

APP_NAME="TapSpaces"
VERSION="$(cat VERSION)"
PROFILE="${NOTARY_PROFILE:-tapspaces}"
APP="build/${APP_NAME}.app"
DIST="dist"
ZIP="${DIST}/${APP_NAME}-${VERSION}.zip"

echo "==> Sürüm ${VERSION}"
./build.sh

# Matched with a shell test rather than `| grep -q`: under `pipefail`, grep
# closing the pipe early makes codesign exit on SIGPIPE, so a successful match
# would fail the check.
SIGNATURE="$(codesign -dvvv "${APP}" 2>&1 || true)"
if [[ "${SIGNATURE}" != *"Authority=Developer ID Application"* ]]; then
    echo "HATA: uygulama Developer ID ile imzalanmamış. Notarization reddedecektir." >&2
    exit 1
fi

mkdir -p "${DIST}"
rm -f "${ZIP}"

# Notarisation takes an archive, not a bundle. ditto preserves the symlinks and
# extended attributes that a plain `zip` would flatten and invalidate the
# signature over.
echo "==> Arşivleniyor"
ditto -c -k --keepParent "${APP}" "${ZIP}"

echo "==> Apple'a gönderiliyor (birkaç dakika sürebilir)"
xcrun notarytool submit "${ZIP}" --keychain-profile "${PROFILE}" --wait

# The ticket is stapled to the bundle, not the archive, so the app has to be
# re-zipped afterwards for the stapled copy to be the one distributed.
echo "==> Onay mührü ekleniyor"
xcrun stapler staple "${APP}"

rm -f "${ZIP}"
ditto -c -k --keepParent "${APP}" "${ZIP}"

# The DMG is the direct-download artifact for the website: a drag-to-install
# window with an Applications symlink. It gets its own signature and its own
# notarisation — Gatekeeper checks the container as well as the app inside.
#
# Styling happens on a read-write image: Finder is scripted to set the window
# size, icon positions and the background (packaging/dmg-background.png,
# regenerated by packaging/render-background.sh when the html changes), the
# result is converted to a compressed read-only image.
#
# The background must be a png — macOS 26's Finder silently ignores the
# classic multi-image tiff — and it only renders after the window is closed
# and reopened, which is why the script cycles the window at the end.
DMG="${DIST}/${APP_NAME}-${VERSION}.dmg"
RW="${DIST}/rw.dmg"
echo "==> DMG hazırlanıyor"
STAGE="$(mktemp -d)"
cp -R "${APP}" "${STAGE}/"
ln -s /Applications "${STAGE}/Applications"
mkdir "${STAGE}/.background"
cp packaging/dmg-background.png "${STAGE}/.background/background.png"
rm -f "${DMG}" "${RW}"
hdiutil create -volname "Tap Spaces" -srcfolder "${STAGE}" \
    -ov -format UDRW -quiet "${RW}"
rm -rf "${STAGE}"

MOUNT=$(hdiutil attach -readwrite -noverify -noautoopen "${RW}" \
    | awk -F'\t' '/Volumes/{print $3}')
cp icon/AppIcon.icns "${MOUNT}/.VolumeIcon.icns"
SetFile -a C "${MOUNT}"

# The disk is addressed by the actual mount name: if a stale "Tap Spaces"
# volume is still mounted the new one comes up as "Tap Spaces 1", and a
# hardcoded name would style the wrong disk.
osascript - "$(basename "${MOUNT}")" <<'OSA'
on run argv
    set volName to item 1 of argv
    tell application "Finder"
        tell disk volName
            open
            set current view of container window to icon view
            set toolbar visible of container window to false
            set statusbar visible of container window to false
            set the bounds of container window to {200, 120, 860, 548}
            set viewOptions to the icon view options of container window
            set arrangement of viewOptions to not arranged
            set icon size of viewOptions to 104
            set text size of viewOptions to 12
            set background picture of viewOptions to file ".background:background.png"
            set position of item "TapSpaces.app" of container window to {165, 195}
            set position of item "Applications" of container window to {495, 195}
            update without registering applications
            delay 1
            close
        end tell
        delay 1
        -- Reopen once: Finder only writes and renders the background after a
        -- fresh read of the window's .DS_Store.
        tell disk volName
            open
            delay 1
            close
        end tell
    end tell
end run
OSA

sync
hdiutil detach "${MOUNT}" -quiet
hdiutil convert "${RW}" -format UDZO -imagekey zlib-level=9 -o "${DMG}" -quiet
rm -f "${RW}"

SIGN_IDENTITY=$(security find-identity -v -p codesigning \
    | grep "Developer ID Application" \
    | head -1 | sed -E 's/.*"(.*)"/\1/')
codesign --force --sign "${SIGN_IDENTITY}" --timestamp "${DMG}"

echo "==> DMG Apple'a gönderiliyor"
xcrun notarytool submit "${DMG}" --keychain-profile "${PROFILE}" --wait
xcrun stapler staple "${DMG}"

echo "==> Doğrulanıyor"
xcrun stapler validate "${APP}"
spctl -a -vvv -t install "${APP}" 2>&1 | sed 's/^/    /'
xcrun stapler validate "${DMG}"

SHA=$(shasum -a 256 "${ZIP}" | awk '{print $1}')
SHA_DMG=$(shasum -a 256 "${DMG}" | awk '{print $1}')
echo
echo "==> Hazır"
echo "    zip   : ${ZIP}"
echo "    sha256: ${SHA}"
echo "    dmg   : ${DMG}"
echo "    sha256: ${SHA_DMG}"
